export const Images = {
  education_journey: require('../experience/assets/education-journey-icon.png'),
  eduArrowIconOne: require('../experience/assets/Arrow-1.png'),
  counselling_services: require('../experience/assets/counselling-services.png'),
  psychometric_tests: require('../experience/assets/psychometric-tests.png'),
  career_library: require('../experience/assets/career-library.png'),
  skill_building: require('../experience/assets/skill-building.png'),
  edu_abacus: require('../experience/assets/edu_abacus.png'),
  counselling_image: require('../experience/assets/counselling-image.png'),
  counsellor_images: require('../experience/assets/counsellor-image.png'),
  faq: require('../experience/assets/faq.png'),
  contact_us: require('../experience/assets/contact-us.png'),
  delete_account: require('../experience/assets/delete_account.png'),
  call: require('../experience/assets/call.png'),
  email: require('../experience/assets/email.png'),
  account_profile: require('../experience/assets/account-profile.png'),
  education_level: require('../experience/assets/EduLevel.png'),
  preffered_education: require('../experience/assets/PreferredEdu.png'),
  psychometric_sample: require('../experience/assets/psychometric-sample.png'),
  education_bg: require('../experience/assets/education-bg.png'),
  education_logo_withname: require('../experience/assets/education-logo-withname.png'),
  collegeIcon: require('../experience/assets/college_icon.png'),
}
